### ISSUE TITLE
The value of process.argv[0] is incorrect

### ISSUE THREAD

**Issue by kuyermqi** [nodejs-mobile/nodejs-mobile#11]
### Version

v16.17.1

### Platform

Android 12, aarch 64

### What steps will reproduce the bug?

```javascript
console.log(process.argv[0]) // => /system/bin/app_process64
```

It will cause an error when calling the child_process module to create a child thread:
```javascript
const { execSync } = require('child_process')
execSync('console.log(0)') // => will throw an error
```

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

The value of process.argv[0] should be dynamic shared library path of node, for example "/path/to/nativeLibs/libnode.so"

### What do you see instead?

The value of process.argv[0] is "/system/bin/app_process64".

### Additional information

This value should be the dynamic shared library path of node, not "/system/bin/app_process64", it will cause an error when calling the child_process module to create a child thread.

![image](https://user-images.githubusercontent.com/38306830/216815997-db799938-e141-4c8b-a490-4ff35c1c6a52.png)

**Comment by staltz** [comment]
Is this issue about `process.argv[0]` or is it about `child_process`?

About `process.argv[0]`, why do you expect it to be `libnode.so`? That `.so` is not an executable so it can't be the first argument (and in fact, it makes little sense to talk about arguments on Android, since the application is not executed from the terminal). It actually makes sense to me that `/system/bin/app_process64` is the first argument because that's the executable that spawns Android Activities, such as your app.

And about `child_process`, it has never been supported in nodejs-mobile: https://code.janeasystems.com/nodejs-mobile/faq#are-all-nodejs-apis-supported-on-mobile

**Comment by kuyermqi** [comment]
Thanks for your reply and I'm sorry for not reading the docs carefully.
Since this works as expected, I will close this issue.
