### ISSUE TITLE
Update Node.js from upstream

### ISSUE THREAD

**Issue by staltz** [nodejs-mobile/nodejs-mobile#2]
> @gmaclennan: the fork is actually from chakra-core still, but I understand it's now built on nodejs. It might be worth doing a big diff from nodejs 12.19.0 to nodejs-mobile, and then doing a big rebase, where we start from nodejs latest, and apply the patch on top of that.

Notes:

- Most of the diff is in the scripts, in Python
- Has Node.js changed their build system? That would be the biggest obstacle
- Has Node.js introduced new dependencies?
- Getting new code to run on iOS is much harder than on Android, given that Android is a Linux
- Node.js version update is usually just one merge commit from upstream

Tasks:

- [ ] Before anything, get it building and the iOS tests running on device
- [ ] Then, attempt to the Node.js version update
- [ ] Make sure it works on iOS
- [ ] Make sure it works on Android
- [ ] Make sure it works with Cordova
- [ ] Make sure it works with React Native

**Comment by gmaclennan** [comment]
The commit at node v12.19.0 is https://github.com/nodejs-mobile/nodejs-mobile/commit/d68bff2e6f4c2a21f37ef3700b0ebadb2337821f (for confirmation see upstream [`v12.19.0`](https://github.com/nodejs/node/commits/v12.19.0))

The diff from node v12.19.0 is https://github.com/nodejs-mobile/nodejs-mobile/compare/d68bff2e6f4c2a21f37ef3700b0ebadb2337821f...mobile-master

There are a few different patches to C++ code to work around platform idiosyncrasies, but it all looks doable. The work will be tracking down where these patches should be made if there are lots of changes upstream, and if there is anything new that breaks Android or iOS then that could take a little while to find.

**Comment by gmaclennan** [comment]
I've kick-started a possible approach to this after attempting a simple merge from upstream and realising a merge would just require a single piece of work resolving merge conflicts that could easily result in errors that are hard to review. Instead with [PR #3](https://github.com/nodejs-mobile/nodejs-mobile/pull/3) I am suggesting manually rebasing the changes from nodejs-mobile onto upstream Node v16.13.2. I have also created a couple of tags [`upstream-node-v12.16.0`]() and [`upstream-node-v12.19.0`]() that reference when upstream was merged into this repo, which can be helpful for viewing comparisons / diffs in Github. This repo started as a fork of Chakra Code but since [`upstream-node-v12.16.0`](https://github.com/nodejs-mobile/nodejs-mobile/tree/upstream-node-v12.16.0) is rebased on [nodejs/node](https://github.com/nodejs/node) (e.g. every commit in `mobile-master` is on top of https://github.com/nodejs/node/tree/v12.16.0, with v12.19.0 merged in later).

I don't have much time to look at this further, but since my head was in this space and I was figuring things out, I thought this initial start might be helpful, but very open to different approaches to doing this!

**Comment by KishanBagaria** [comment]
From the Gitter chat: @Qualphey got v17.4.0 compiling at https://gitlab.com/Qualphey/nodejs-mobile-build by using patches from https://github.com/termux/termux-packages/tree/master/packages/nodejs

**Comment by agarcia17** [comment]
@KishanBagaria, I'm not familiar with the Procursus project; do you happen to have any instructions/pointers of how to leverage that project to get a nodejs-mobile type of build to get nodejs running on iOS and/or Android?

**Comment by KishanBagaria** [comment]
Nope but maybe @1conan can chime in.

**Comment by KishanBagaria** [comment]
We have a bounty on getting Node.js 16 or newer working on iOS with nodejs-mobile. If you're interested, my email is in profile.

**Comment by staltz** [comment]
PR #9 was merged to update Node.js to 16.17.1, now I'm working on cutting out a release.
